appname="文本操作"
appver="1.0"
appcode="1"
appsdk="22"
path_pattern="lua"
packagename="org.alittlemc.bug"
theme="Theme_DeviceDefault_Light_NoActionBar_TranslucentDecor"
developer="alittlemc"
description=""
debugmode=true
user_permission={
  "WRITE_EXTERNAL_STORAGE"
}
